#!/usr/bin/env bash
# Renders the Codex agent definitions (.codex/agents/*.toml) from the plugin's Claude-format agents.
# Codex plugins cannot carry agents, so the template ships these files; tests/codex-agents.sh fails
# when they differ from a fresh render. Usage: scripts/gen-codex-agents.sh [<out dir>]
set -eu
repo=$(cd "$(dirname "$0")/.." && pwd -P)
out=${1:-"$repo/template/{% if use_codex %}.codex{% endif %}/agents"}
src=$repo/plugins/harness/agents
# Model ids and efforts from spec §3 Spike findings F12 (the Codex column of docs/harness/models.md).
STRONG_MODEL='gpt-6-luna' STRONG_EFFORT=high
FAST_MODEL='gpt-6-luna' FAST_EFFORT=medium
mkdir -p "$out"

field() { sed -n "2,/^---\$/s/^$1: //p" "$2" | head -n 1; }
body() { awk 'n >= 2 { print } /^---$/ { n++ }' "$1"; }

emit() { # <src md> <name> <model> <effort> <sandbox>
  local b
  b=$(body "$1")
  case "$b" in *"'''"*) echo "gen-codex-agents: $1 contains ''' and cannot be a TOML literal string" >&2; exit 1 ;; esac
  {
    printf '# Generated by scripts/gen-codex-agents.sh from plugins/harness/agents/%s. Do not edit.\n' "$(basename "$1")"
    printf 'name = "%s"\n' "$2"
    printf 'description = %s\n' "$(field description "$1" | jq -Rs 'rtrimstr("\n")')"
    printf 'model = "%s"\n' "$3"
    printf 'model_reasoning_effort = "%s"\n' "$4"
    printf 'sandbox_mode = "%s"\n' "$5"
    printf "developer_instructions = '''\n%s\n'''\n" "$b"
  } > "$out/$2.toml"
}

emit "$src/implementer.md" harness-implementer "$FAST_MODEL" "$FAST_EFFORT" workspace-write
emit "$src/reviewer.md" harness-reviewer "$STRONG_MODEL" "$STRONG_EFFORT" read-only
emit "$src/reviewer.md" harness-reviewer-intermediate "$FAST_MODEL" "$STRONG_EFFORT" read-only
